# Generated by Django 5.1.3 on 2024-11-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longtitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('phone', models.CharField(max_length=15)),
                ('logoPic', models.CharField(max_length=225)),
                ('bgPic', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwdHashed', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
